### ISSUE TITLE
Cocoapods not found

### ISSUE THREAD

**Issue by ahmedraad** [krimpedance/KRPullLoader#1]
When try to install via Cocoapods

`[!] Unable to find a specification for KRPullLoader`

then i used this and it work !

` pod 'KRPullLoader', :git => 'https://github.com/krimpedance/KRPullLoader.git' `

**Comment by krimpedance** [comment]
@ahmedraad 
Please update your cocoapods master repo.
https://stackoverflow.com/a/32850706

**Comment by krimpedance** [comment]
no response.
