### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by VizenkoRoman** [krimpedance/KRPullLoader#10]
if the smudge ends less than 0.2 s then the bug

 if completionHandler call without delay.

      if type == .loadMore {

         switch state {
         case let .loading(completionHandler):
            pullLoadView.messageLabel.text = "Updating..."

        //    DispatchQueue.main.asyncAfter(deadline: DispatchTime.now()+1) {
               completionHandler()
       //        self.tableView.reloadData()
          //  }
         default: break
         }
         return
      }

**Comment by VizenkoRoman** [comment]
fixed code:
//KRPullLoader.swift

need to change lines  139  140 

139       startLoading()
140       state = .loading(completionHandler: endLoading)

**Comment by krimpedance** [comment]
@VizenkoRoman 
I'm sorry for the delay in replying.
Please try ver.1.1.1

**Comment by krimpedance** [comment]
#11
