### ISSUE TITLE
Refresh View issue

### ISSUE THREAD

**Issue by muthusabarinathan** [krimpedance/KRPullLoader#11]
I have UItableview inside UiCollectionView Cell and adding both refresh and loadmore views to uitableview.On Refresh completes,uitableview scrolled up around 50 pts

**Comment by Sethu171988** [comment]
I am also facing the same issue as mentioned by @muthusabarinathan

**Comment by krimpedance** [comment]
@muthusabarinathan @Sethu171988 
When calling a handler about 0.2 seconds later, does nothing happen?
If so, I'd be able to correct the bug early.

**Comment by krimpedance** [comment]
@muthusabarinathan @Sethu171988 
Please try `ver.1.1.1`.

**Comment by Sethu171988** [comment]
@krimpedance - Thank you for a quick response. There is still some flickering that happens when you scroll down but this version is much better than the previous one

**Comment by lupugabriel** [comment]
hey, i tried 1.1.1 and for me it's the same thing. whenever i pull refresh when it finished the tableview moves 50p up.

**Comment by lupugabriel** [comment]
a solution :
case let .loading(completionHandler):
            pullLoadView.messageLabel.text = "Updating..."
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now()+1) {
                completionHandler()
                self.tableView.removePullLoadableView(self.refreshView)
                self.loadData()
                self.tableView.addPullLoadableView(self.refreshView, type: .refresh)
            }
        }

**Comment by krimpedance** [comment]
@lupugabriel 
Please try [dev](https://github.com/krimpedance/KRPullLoader/tree/dev) branch.

**Comment by krimpedance** [comment]
I close this because there is no response.
I think the problem was solved by `1.1.2` .
