### ISSUE TITLE
shows only last item ?

### ISSUE THREAD

**Issue by ismailtosun** [krimpedance/KRPullLoader#13]
When I do load more , it's show lastrow. I want to show row that before I loaded more 
How can I do this ?

**Comment by krimpedance** [comment]
@ismailtosun 
I reconsider a code and correct to this problem.

**Comment by krimpedance** [comment]
@ismailtosun 
Please try [dev](https://github.com/krimpedance/KRPullLoader/tree/dev) branch.

**Comment by krimpedance** [comment]
@ismailtosun 
I close this because there is no response.
I think the problem was solved by `1.1.2` .
