### ISSUE TITLE
pullLoadView method is not called  if scrollView.contentSize.height less then  scrollView.bounds.height 

### ISSUE THREAD

**Issue by daryachuiko** [krimpedance/KRPullLoader#14]
there is validation:

self.isHidden = scrollView.bounds.height > (scrollView.contentSize.height + scrollView.contentInset.top + scrollView.contentInset.bottom)

so if my content just few cell self.isHidden == true and I cant load info cause 

if self.isHidden { return }
self.updateState()
 
so update state won't call and delegate's method won't be called as well

So it will be better if in this case you continue send state .loading

**Comment by krimpedance** [comment]
@daryachuiko show #7

**Comment by daryachuiko** [comment]
@krimpedance , ok, thank you for quick response!
