### ISSUE TITLE
crash on ios 10 ( 10.3.3) after dismissing view

### ISSUE THREAD

**Issue by daryachuiko** [krimpedance/KRPullLoader#15]
On ios 10 ( 10.3.3) app crashes with logs:
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x1048e8c00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x17443a540> (
<NSKeyValueObservance 0x17484c7b0: Observer: 0x1728779c0, Key path: contentOffset, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x17484c720>
<NSKeyValueObservance 0x17484ca50: Observer: 0x174c6d200, Key path: contentSize, Options: <New: NO, Old: NO, Prior: NO> Context: 0x0, Property: 0x17484c990>
)'

Issue is fixed by removing KRPullLoadView in viewWillDisappear, but for clean code will be better to fix this issue from library side

Thank you

**Comment by krimpedance** [comment]
@daryachuiko 
Whether #8 is not helpful to you?

**Comment by daryachuiko** [comment]
@krimpedance, it's fix the issue, so will you something do with this issue from your side ?

**Comment by krimpedance** [comment]
@daryachuiko 
I will investigate.

**Comment by krimpedance** [comment]
fixed in `1.1.3`
