### ISSUE TITLE
Crash due to  self.removeFromSuperview()

### ISSUE THREAD

**Issue by jabransiddiqui** [krimpedance/KRPullLoader#16]
Error : warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

screen shot
<img width="827" alt="screen shot 2018-03-31 at 3 53 56 pm" src="https://user-images.githubusercontent.com/23705554/38162557-6230fc1e-34fc-11e8-863b-3a016a2b94dd.png">

**Comment by krimpedance** [comment]
@jibransiddiqui 
Please try the latest version.

**Comment by krimpedance** [comment]
no response
