### ISSUE TITLE
LoadMore activityIndicator incorrect position after completion

### ISSUE THREAD

**Issue by askarimov** [krimpedance/KRPullLoader#2]
Hi, 
If I add new cells and reload tableview after loadMore completes, activity indicator stays at original position. Please see the attached screenshot.

![simulator screen shot jul 7 2017 01 59 49](https://user-images.githubusercontent.com/1710021/27930343-08466a3e-62b8-11e7-9b3a-22e18d2dacd9.png)

**Comment by krimpedance** [comment]
@askarimov 
Oh..
I'll correct immediately.

**Comment by krimpedance** [comment]
@askarimov 
I corrected the bug and released ver.1.0.1.

thanks.

**Comment by askarimov** [comment]
Great! Tahnks. Closing
