### ISSUE TITLE
How to manually refresh the KRPullLoadView

### ISSUE THREAD

**Issue by MandeepSingh1** [krimpedance/KRPullLoader#20]
I have the table view, and we have the button in the navigation bar. So when ever user will click on that button I have to call the KRPullLoadView manually so that loader view will be visible to the user and am able to call the service function.

How can I achieve this functionality, please lemme know if you understand my point.

Thanks

**Comment by krimpedance** [comment]
@MandeepSingh1 
I understand your point.
But This lib doesn't have its function now.
When tap the button, I assumed that progressHUD is indicated.

However, there are some people who think like you.
So, I implement its function  in the near future.

**Comment by LightNightCode** [comment]
I added this method to simulate a manual refresh 😊
// 模拟手动刷新

func manualStartLoading() -> Void {
        
        guard let scrollView = self.scrollView
            else { return }
        
         if case .loading = self.state { return }
        
        // 找到阈值
        let threshold = (scrollDirection == .vertical) ? bounds.height : bounds.width
       
        // 模拟设置滑动距离
        switch type {
        case .refresh:
            switch scrollDirection {
            case .vertical:
                scrollView.distanceOffset.y = -threshold - 1
            case .horizontal:
                scrollView.distanceOffset.x = -threshold - 1
            }
        case .loadMore:
            switch scrollDirection {
            case .vertical:
                scrollView.distanceEndOffset.y = -threshold - 1
            case .horizontal:
                scrollView.distanceEndOffset.x = -threshold - 1
            }
        }
        
        // 模拟更改载入状态
        state = .loading(completionHandler: {[weak self] in
            self?.endLoading()
        })
        
        startLoading()
    }
}

I hope to help you❤️.

**Comment by krimpedance** [comment]
@MandeepSingh1  @LightNightCode 

Sorry I'm late.
Please try `1.3.0`. ( `tableView.pullToRefresh` )
