### ISSUE TITLE
How to change color of activity indicator

### ISSUE THREAD

**Issue by Cez95** [krimpedance/KRPullLoader#22]
I am trying to change the color of the activity indicator when I use the loadMore functionality. The issue is that the color is persistent on not changing. I am building the UI Programmatically and this is my implementation....

    private let paginateControl: KRPullLoadView = {
        let refresh = KRPullLoadView()
        refresh.activityIndicator.tintColor = UIColor.white
        refresh.activityIndicator.color = UIColor.white
        return refresh
    }()

Is there an easy way I can change the indicator to white?

**Comment by krimpedance** [comment]
@Cez95 
Please create custom refresh view like [KRPullLoadView](https://github.com/krimpedance/KRPullLoader/blob/master/KRPullLoader/Classes/KRPullLoadView.swift) and [HorizontalPullLoadView](https://github.com/krimpedance/KRPullLoader/blob/master/DEMO/KRPullLoaderDemo/HorizontalPullLoadView.swift).

or please set colors after `KRPullLoadView.layoutSubviews()`.

**Comment by krimpedance** [comment]
no response
