### ISSUE TITLE
There may be a memory leak

### ISSUE THREAD

**Issue by LightNightCode** [krimpedance/KRPullLoader#23]
There may be a memory leak
<img width="719" alt="leak" src="https://user-images.githubusercontent.com/13429912/49575654-324e7c00-f97e-11e8-85e6-7c07c779a4f5.png">

**Comment by LightNightCode** [comment]
I fix it, may solve the problem. 140 line: loading(completionHandler: ()->Void), I use [weak self].
<img width="1021" alt="2018-12-06 6 32 59" src="https://user-images.githubusercontent.com/13429912/49578741-65e0d480-f985-11e8-9bdd-92ca7f18b972.png">

**Comment by krimpedance** [comment]
@LightNightCode 
I think the version you're using is old.

**Comment by krimpedance** [comment]
@LightNightCode 
No response.
