### ISSUE TITLE
A rename error occurs when using abstract_target.

### ISSUE THREAD

**Issue by devny** [krimpedance/KRPullLoader#24]
Hi!
A rename error occurs when using abstract_target.
KRPullLoader.swift 
open func setup {
activityIndicator.style -> occured!!!
}

**Comment by krimpedance** [comment]
@devny 
Is `abstract_target` Podfile syntax?
What is the Swift version and this lib version?

**Comment by devny** [comment]
Swift version is 4.2.1
this lib version is 1.2.0

**Comment by krimpedance** [comment]
@devny 
I tried abstract_target, bud clean.
Isn't there a possibility of the other parts?
Please show me error messages. (texts or screenshots)

**Comment by krimpedance** [comment]
no response.
